package Javascript_MirukenJs.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = 'a75e48dc-cdf3-49f4-bb25-b82d658ae038' (id = 'Javascript_MirukenJs_Core_Deploy')
in the project with uuid = '8afe80d3-49b6-4e67-8c8e-126b73c04bd6' and delete the patch script.
*/
create("8afe80d3-49b6-4e67-8c8e-126b73c04bd6", Project({
    uuid = "a75e48dc-cdf3-49f4-bb25-b82d658ae038"
    id = "Javascript_MirukenJs_Core_Deploy"
    parentId = "Javascript_MirukenJs_Core"
    name = "Deployment"
}))

