package Javascript_MirukenJs.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = 'dbca4081-2559-48ea-be4a-695fe6183d68' (id = 'Javascript_MirukenJs_Core_Deploy_Core')
in the project with uuid = 'a75e48dc-cdf3-49f4-bb25-b82d658ae038' and delete the patch script.
*/
create("a75e48dc-cdf3-49f4-bb25-b82d658ae038", Project({
    uuid = "dbca4081-2559-48ea-be4a-695fe6183d68"
    id = "Javascript_MirukenJs_Core_Deploy_Core"
    parentId = "Javascript_MirukenJs_Core_Deploy"
    name = "Core"
}))

