package Javascript_Packages_MirukenJS.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '12DB5C1F-FB26-40ED-8F42-662DB4EE8124' (id = 'Javascript_Packages_MirukenJs_Validate')
accordingly, and delete the patch script.
*/
changeProject("12DB5C1F-FB26-40ED-8F42-662DB4EE8124") {
    params {
        expect {
            param("MajorVersion", "0")
        }
        update {
            param("MajorVersion", "2")
        }
    }
}
