package Javascript_Packages_MirukenJS.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'DCF5584D-CBD2-46F0-A92F-BBE5076BBDBC' (id = 'Javascript_Packages_MirukenJs_MVC')
accordingly, and delete the patch script.
*/
changeProject("DCF5584D-CBD2-46F0-A92F-BBE5076BBDBC") {
    check(name == "MVC Project") {
        "Unexpected name: '$name'"
    }
    name = "Mvc Project"
}
