package Javascript_Packages_MirukenES5.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with uuid = '2946284d-8d74-4e4b-9c7a-cc5cad66a469_PackageVCSRoot' (id = 'mirukenEs5_PackageVCSRoot')
accordingly and delete the patch script.
*/
changeVcsRoot("2946284d-8d74-4e4b-9c7a-cc5cad66a469_PackageVCSRoot") {
    val expected = GitVcsRoot({
        uuid = "2946284d-8d74-4e4b-9c7a-cc5cad66a469_PackageVCSRoot"
        id = "mirukenEs5_PackageVCSRoot"
        name = "git@github.com:Miruken-ES5/miruken-es5.git_Package"
        url = "git@github.com:Miruken-ES5/miruken-es5.git"
        branch = "master"
        agentCleanPolicy = GitVcsRoot.AgentCleanPolicy.ALWAYS
        authMethod = uploadedKey {
            uploadedKey = "provenstyle"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = "+:refs/heads/(master)"
        authMethod = uploadedKey {
        }
    }

}
