package Javascript_Packages_MirukenES5.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = 'f6e70694-e0b0-4c32-85b7-c55882623346' (id = 'Javascript_MirukenEs5_Mirken_mirukenEs5_MirukenEs5')
in the project with uuid = '2992abf2-e74a-44e6-950a-30f41d7bfff5_mirukenEs5' and delete the patch script.
*/
create("2992abf2-e74a-44e6-950a-30f41d7bfff5_mirukenEs5", GitVcsRoot({
    uuid = "f6e70694-e0b0-4c32-85b7-c55882623346"
    id = "Javascript_MirukenEs5_Mirken_mirukenEs5_MirukenEs5"
    name = "miruken-es5"
    url = "git@github.com:Miruken-ES5/miruken-es5.git"
    authMethod = uploadedKey {
        uploadedKey = "provenstyle"
    }
}))

