package Javascript_MirukenJs.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with uuid = '67da91fa-b5cd-4d60-88b3-06fa4148213d' (id = 'Javascript_MirukenJs_Core_Deploy_Core_DeployRelease')
in the project with uuid = 'dbca4081-2559-48ea-be4a-695fe6183d68' and delete the patch script.
*/
create("dbca4081-2559-48ea-be4a-695fe6183d68", BuildType({
    uuid = "67da91fa-b5cd-4d60-88b3-06fa4148213d"
    id = "Javascript_MirukenJs_Core_Deploy_Core_DeployRelease"
    name = "Deploy Release"
}))

