package Javascript_MirukenJs.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '983f8966-9172-49d6-89b2-4ca5acbe22f8_mirukenCore_DeployPreRelease' (id = 'Javascript_MirukenJs_Core2_mirukenCore_DeployPreRelease')
accordingly and delete the patch script.
*/
changeBuildType("983f8966-9172-49d6-89b2-4ca5acbe22f8_mirukenCore_DeployPreRelease") {
    expectSteps {
    }
    steps {
        insert(0) {
            script {
                name = "Pack"
                scriptContent = "%npm% pack"
            }
        }
    }
}
