package Javascript_MirukenJs.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with uuid = 'ab6075b6-05a6-4daa-b16f-d1a74cfb352b' (id = 'Javascript_MirukenJs_Core_Deploy_Core_DeployPreRelease')
in the project with uuid = 'dbca4081-2559-48ea-be4a-695fe6183d68' and delete the patch script.
*/
create("dbca4081-2559-48ea-be4a-695fe6183d68", BuildType({
    uuid = "ab6075b6-05a6-4daa-b16f-d1a74cfb352b"
    id = "Javascript_MirukenJs_Core_Deploy_Core_DeployPreRelease"
    name = "Deploy PreRelease"
}))

