package Javascript_Packages_MirukenJS.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'c5fd1e3a-3ee5-4adb-9695-b4fc50557247_mirukenCallback_DeployRelease' (id = 'Javascript_Packages_MirukenJs_Callback_mirukenCallback_DeployRelease')
accordingly and delete the patch script.
*/
changeBuildType("c5fd1e3a-3ee5-4adb-9695-b4fc50557247_mirukenCallback_DeployRelease") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
